apiVersion: v1
kind: Service
metadata:
  name: {{ include "sage-app2.fullname" . }}
  labels:
    {{- include "sage-app2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "sage-app2.selectorLabels" . | nindent 4 }}




